"""created ticket table

Revision ID: ac5b27dde557
Revises: af9e7ca113c1
Create Date: 2019-03-16 21:36:31.120197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5b27dde557'
down_revision = 'af9e7ca113c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('ticketID', sa.Integer(), nullable=False),
    sa.Column('vType', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('licensePlateNumber', sa.String(length=8), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('ticketID')
    )
    op.create_index(op.f('ix_ticket_timestamp'), 'ticket', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_timestamp'), table_name='ticket')
    op.drop_table('ticket')
    # ### end Alembic commands ###
