"""created vehicle table

Revision ID: e4f67dab6762
Revises: ac5b27dde557
Create Date: 2019-03-16 22:15:49.626626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f67dab6762'
down_revision = 'ac5b27dde557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('licensePlateNumber', sa.String(length=8), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=True),
    sa.Column('make', sa.String(length=20), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], ),
    sa.PrimaryKeyConstraint('licensePlateNumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    # ### end Alembic commands ###
